package entity;
// Generated Sep 11, 2014 2:17:32 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer idUser;
     private String username;
     private String password;
     private boolean admin;
     private Set purchaseses = new HashSet(0);

    public Users() {
    }

	
    public Users(String username, String password, boolean admin) {
        this.username = username;
        this.password = password;
        this.admin = admin;
    }
    public Users(String username, String password, boolean admin, Set purchaseses) {
       this.username = username;
       this.password = password;
       this.admin = admin;
       this.purchaseses = purchaseses;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isAdmin() {
        return this.admin;
    }
    
    public void setAdmin(boolean admin) {
        this.admin = admin;
    }
    public Set getPurchaseses() {
        return this.purchaseses;
    }
    
    public void setPurchaseses(Set purchaseses) {
        this.purchaseses = purchaseses;
    }




}


