package entity;
// Generated Sep 11, 2014 2:17:32 AM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Purchases generated by hbm2java
 */
public class Purchases  implements java.io.Serializable {


     private Integer idPurchase;
     private Users users;
     private Set detailses = new HashSet(0);

    public Purchases() {
    }

	
    public Purchases(Users users) {
        this.users = users;
    }
    public Purchases(Users users, Set detailses) {
       this.users = users;
       this.detailses = detailses;
    }
   
    public Integer getIdPurchase() {
        return this.idPurchase;
    }
    
    public void setIdPurchase(Integer idPurchase) {
        this.idPurchase = idPurchase;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public Set getDetailses() {
        return this.detailses;
    }
    
    public void setDetailses(Set detailses) {
        this.detailses = detailses;
    }




}


